# Generated by Django 3.0.6 on 2020-06-19 18:29

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campuses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='公司/部门')),
                ('address', models.CharField(blank=True, max_length=512, null=True, verbose_name='详细地址')),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='请输入真实姓名', max_length=32, verbose_name='姓名')),
                ('customer_type', models.CharField(choices=[('person', '个人'), ('company', '公司')], default='person', max_length=16, null=True, verbose_name='用户类型')),
                ('phone', models.BigIntegerField(help_text='请确认手机号正确', verbose_name='手机号')),
                ('qq', models.CharField(blank=True, max_length=64, null=True, verbose_name='QQ')),
                ('qq_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='QQ昵称')),
                ('source', models.CharField(choices=[('qq', 'qq群'), ('referral', '内部转介绍'), ('website', '官方网站'), ('baidu_ads', '百度推广'), ('office_direct', '直接上门'), ('WoM', '口碑'), ('others', '其它')], default='qq', max_length=64, verbose_name='客户来源')),
                ('course', multiselectfield.db.fields.MultiSelectField(choices=[('MT4414/MT4414TE', 'MT4414/MT4414TE'), ('GL070/Gl070E', 'GL070/Gl070E'), ('GL100/Gl100E', 'GL100/Gl100E'), ('GH070/GH070E', 'GH070/GH070E'), ('GH104/GH104E', 'GH104/GH104E'), ('F080/F080E', 'F080/F080E'), ('HMIothers', 'HMI的其他产品'), ('others', 'HMI产品外的其他产品')], max_length=95, null=True, verbose_name='咨询产品')),
                ('product_type', models.CharField(choices=[('HMI', 'HMI'), ('PLC', '可编程控制器'), ('Electric', '步进电机'), ('others', '其它')], default='HMI', max_length=64, verbose_name='产品类型')),
                ('customer_note', models.TextField(blank=True, null=True, verbose_name='客户备注')),
                ('status', models.CharField(choices=[('buyed', '已购买'), ('unbuyed', '未购买'), ('buying', '商讨中')], default='unbuyed', help_text='选择客户此时的状态', max_length=64, verbose_name='状态')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='咨询日期')),
                ('last_consult_date', models.DateField(auto_now_add=True, verbose_name='最后跟进日期')),
                ('next_date', models.DateField(blank=True, null=True, verbose_name='预计再次跟进时间')),
            ],
            options={
                'verbose_name': '客户信息表',
                'verbose_name_plural': '客户信息表',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProductList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(choices=[('MT4414/MT4414TE', 'MT4414/MT4414TE'), ('GL070/Gl070E', 'GL070/Gl070E'), ('GL100/Gl100E', 'GL100/Gl100E'), ('GH070/GH070E', 'GH070/GH070E'), ('GH104/GH104E', 'GH104/GH104E'), ('F080/F080E', 'F080/F080E'), ('HMIothers', 'HMI的其他产品'), ('others', 'HMI产品外的其他产品')], max_length=64, verbose_name='产品名称')),
                ('semester', models.CharField(max_length=32, verbose_name='类型')),
                ('price', models.IntegerField(default=1000, verbose_name='价格')),
                ('memo', models.CharField(blank=True, max_length=100, null=True, verbose_name='说明')),
                ('start_date', models.DateField(verbose_name='开售日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='停产日期')),
                ('product_type', models.CharField(blank=True, choices=[('HMI', 'HMI'), ('PLC', '可编程控制器'), ('Electric', '步进电机'), ('others', '其它')], max_length=64, null=True, verbose_name='产品类型')),
                ('campuses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supercrm.Campuses', verbose_name='部门')),
            ],
        ),
        migrations.CreateModel(
            name='Productsituation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('perfect', '完美'), ('good', '良好'), ('soso', '一般'), ('bad', '差'), ('verybad', '极差')], max_length=32, verbose_name='产品情况')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='日期')),
                ('campuses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supercrm.Campuses', verbose_name='部门归属')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16)),
                ('password', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=16)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appraise', models.IntegerField(blank=True, choices=[(100, 'A+'), (90, 'A'), (85, 'B+'), (80, 'B'), (70, 'B-'), (60, 'C+'), (50, 'C'), (40, 'C-'), (0, ' D'), (-1, 'N/A'), (-100, 'COPY'), (-1000, 'FAIL')], default=100, null=True, verbose_name='评价')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='备注/其他反馈')),
                ('score_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='购买日期')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supercrm.Customers', verbose_name='客户名称')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supercrm.ProductList', verbose_name='产品名称')),
                ('situation', models.ManyToManyField(blank=True, to='supercrm.Productsituation', verbose_name='产品情况')),
            ],
        ),
        migrations.AddField(
            model_name='productsituation',
            name='leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supercrm.UserInfo', verbose_name='负责人'),
        ),
        migrations.AddField(
            model_name='productsituation',
            name='re_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supercrm.ProductList', verbose_name='产品名称'),
        ),
        migrations.AddField(
            model_name='productlist',
            name='saler',
            field=models.ManyToManyField(to='supercrm.UserInfo', verbose_name='对应销售'),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('why_us', models.TextField(blank=True, default=None, max_length=1024, null=True, verbose_name='为什么选择我们的产品')),
                ('enrolled_date', models.DateTimeField(auto_now_add=True, verbose_name='购买日期')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('delete_status', models.BooleanField(default=False, verbose_name='删除状态')),
                ('contract_approved', models.BooleanField(default=False, help_text='盛和通过后开始生成合同', verbose_name='已审核')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supercrm.Customers', verbose_name='客户名称')),
                ('product', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='supercrm.ProductList', verbose_name='购买产品')),
            ],
        ),
        migrations.AddField(
            model_name='customers',
            name='consultant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='supercrm.UserInfo', verbose_name='销售'),
        ),
        migrations.AddField(
            model_name='customers',
            name='introduce_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supercrm.Customers', verbose_name='转介绍自客户'),
        ),
        migrations.AddField(
            model_name='customers',
            name='product_list',
            field=models.ManyToManyField(blank=True, to='supercrm.ProductList', verbose_name='购买的产品'),
        ),
        migrations.CreateModel(
            name='ConsultRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(verbose_name='跟进内容')),
                ('status', models.CharField(choices=[('A', '近期无购买计划'), ('B', '1个月内购买'), ('C', '2周内购买'), ('D', '1周内购买'), ('E', '定金'), ('F', '全款'), ('G', '无效')], help_text='选择客户此时的状态', max_length=16, verbose_name='跟进状态')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='跟进日期')),
                ('delete_status', models.BooleanField(default=False, verbose_name='删除状态')),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='supercrm.UserInfo', verbose_name='跟进人')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supercrm.Customers', verbose_name='所咨询的客户')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='productlist',
            unique_together={('course', 'semester', 'campuses')},
        ),
    ]
