# Generated by Django 3.0.6 on 2020-06-20 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supercrm', '0002_auto_20200620_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='score_date',
            field=models.DateTimeField(auto_now=True, verbose_name='反馈日期'),
        ),
    ]
