# Generated by Django 3.0.6 on 2020-06-20 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supercrm', '0003_auto_20200620_1817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='score_date',
            new_name='date',
        ),
    ]
