# Generated by Django 3.0.6 on 2020-06-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supercrm', '0004_auto_20200620_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='反馈日期'),
        ),
    ]
