# Generated by Django 3.0.6 on 2020-06-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
        ('supercrm', '0005_auto_20200620_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='roles',
            field=models.ManyToManyField(to='rbac.Role'),
        ),
    ]
