# Generated by Django 3.0.6 on 2020-06-22 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_auto_20200623_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='icon',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
